language: dart

dart:
  - dev
  - 2.0.0

dart_task:
  - test: -p vm
  - test: -p chrome
  - dartanalyzer

matrix:
  include:
    # Only validate formatting using the dev release
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task:
        dartanalyzer: --fatal-infos --fatal-warnings .
    - dart: 2.0.0
      dart_task:
        dartanalyzer: --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
