include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    prefer_spread_collections: ignore

linter:
  rules:
    - avoid_private_typedef_functions
